version: '4'
services:
  deployer-server:
    build:
      context: Deployer
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      servers-net:
        ipv4_address: 192.168.3.30
    depends_on:
      - first-remote
      - second-remote
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Добавляем эту строку для доступа к Docker на хосте

  first-remote:
    tty: true
    build:
      context: RemoteHost
      dockerfile: Dockerfile
    networks:
      servers-net:
        ipv4_address: 192.168.3.31

  second-remote:
    tty: true
    build:
      context: RemoteHost
      dockerfile: Dockerfile
    networks:
      servers-net:
        ipv4_address: 192.168.3.32

networks:
  servers-net:
    ipam:
      config:
        - subnet: 192.168.3.0/24
